### ISSUE TITLE
Maximum uptime (+ updating)

### ISSUE THREAD

**Issue by Yamnasm** [syssykat/talk-to-humans#11]
Downtime is deadtime, so to keep users chatting, the bot must be hosted _**dedicatedly**_.

Connect the dedicated hosting to a "Live Branch" on GitHub that will allow us to update the bot easily. Any other development to the bot will be partaken in a "Dev Branch", and once the development is as bug-free as we see it, pushing the update to the "Live Branch".

**Should the "Dev Branch" use a different bot + token to allow the Live bot to run without disturbance?**

**Do I need to learn Git? How difficult is it without learning Git?**

**Comment by syssykat** [comment]
Created a dev branch and separate Discord bot. Added to the Discord server and token available when you ask me for it.

You got Github Desktop so you should be fine. Gonna find out how to push one branch to another without (m e r g i n g)

Also be less professional in the dev version. Nice.
