### ISSUE TITLE
Recipient sees !commands made by user.

### ISSUE THREAD

**Issue by Yamnasm** [syssykat/talk-to-humans#5]
Commands like !disconnect are being sent as a message to the recipient. Maybe on_message needs to pass messages that start with "!" regardless if its a command or not

**Comment by Yamnasm** [comment]
https://media.discordapp.net/attachments/350072384142704652/442327027698237440/unknown.png

**Comment by syssykat** [comment]
Created if-else that checks if the message starts with the command prefix. Fixed.
