### ISSUE TITLE
Spamming causes "rate limit exhaustion".

### ISSUE THREAD

**Issue by Yamnasm** [syssykat/talk-to-humans#8]
Users that spam cause this error:
`A rate limit bucket has been exhausted`

Maybe have an embedded message that tells the spamming-user to chill the fuck out.

_edit_
All messages actually get sent through eventually, but it takes a while for the bucket(?) to be reset.

**Comment by Yamnasm** [comment]
This bug is apparent even with one user spamming on one connection. If messages are sent normally but with a larger number of connections, does this problem still happen? Does sharding fix this?

**Comment by syssykat** [comment]
Unfixable. It's Discord's fundamental message limiting. Don't even bother trying to change anything because it'll all lead to a dark hole where nothing is solved.
