### ISSUE TITLE
Reports and how they will work.

### ISSUE THREAD

**Issue by Yamnasm** [syssykat/talk-to-humans#9]
# Report Log Header:

`<salt> <time(:ddmmyyhhmm:)> <reporting_user_id> <random #: 1 or 2> <reported_user_id>`
_This is then encrypted using an admin-decided password_
Random number decides which T2H_name is given to the reported user (rather than make the reported user always the second name)
### Example:
```
6843378521884185243843847624216843258493993247
```

# Report Log Body:

Interchangable names, and are kept in names.db as `1:2` (`alice:bob`, `mary:david`, `lucy:jack`, etc)
Which number the reported user is depends on the T2H_Report_Snowflake

This is what the moderator would see when opening the `.log` file:
### Example:
```
[      bob]: hello.
[    alice]: hello.
[      bob]: I am being a reportable user.
[      bob]: I hate you.
[    alice]: consider yourself reported, fine sir.
[      bob]: cheers.
```

# Moderator Action:

Moderator reads Report `.log` file, and determines guilt of either party or both.

Once guilt is found, the moderator would use !mod r <report_ID> <alice, bob> (or both).
_Report_ID is just a chronological ID: `000001`, `000002`, `000003`, etc_

The T2H_Report_Snowflake would then be passed into mod_bot, decrypted, guilty-party identified with user_ID, then sent forward into a database. If they are already in the database, an integer is kept next to their user_id that increments per guilty-report. This database is permanent, but hidden.

Punishments for users the surpass certain integers on their guilt-record will be automatically dealt punishments (temp banning, banning, public mutiliation, etc). Punishments in progress could just be held in their own `.log` file, that has a date-attribute next to the user_id. Once that date is in the past, the punishment is complete, and the entry on the log is deleted.

Eventually we'll just get a VAC-like machine learning bot that will punish people live during their chat with no human interaction, except for the SWAT team the bot will send to their home to beat them to death for breaking the rules.

**Comment by syssykat** [comment]
Shouldn't worry about any of this right now. Gonna close this issue since report functionality was added and it works.

**Comment by syssykat** [comment]
Do want to comment that the "moderation" section of your comment is good and we will definitely implement that as means of punishing users.
